[package]
name = "downloader"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[dependencies]
scoped_threadpool = "*"
crossbeam = "*"
hyper = "*"
quick-error = "*"
thread-id = "*"
