[package]
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
name = "downloader"
version = "0.1.0"

[dependencies]
clap = "2.6.0"
crossbeam = "*"
hyper = "*"
number_prefix = "0.2.5"
quick-error = "*"
rustbox = "0.8.1"
scoped_threadpool = "*"
thread-id = "*"
